# Generated by Django 5.2.5 on 2025-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpsq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="preference",
            field=models.CharField(
                choices=[
                    ("nothing", "Nothing - Just report and move on"),
                    ("notification", "Be notified when resolved"),
                    ("updates", "Get progress updates throughout"),
                    ("yes_would_use", "Yes, I would"),
                    ("no_wouldnt_use", "No, I wouldn't"),
                    ("not_sure", "Not sure"),
                ],
                db_index=True,
                help_text="User's preferred level of engagement",
                max_length=20,
            ),
        ),
    ]
