# Generated by Django 5.2.5 on 2025-08-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpsq", "0004_pretotypecomment_pretotypeissuestatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pretotypeissue",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to uploaded image if using external storage",
                null=True,
            ),
        ),
    ]
