# Generated by Django 5.2.5 on 2025-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpsq", "0005_alter_pretotypeissue_image_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pretotypeissue",
            name="pretotype_i_has_ima_99cf91_idx",
        ),
        migrations.AddField(
            model_name="pretotypeanalytics",
            name="issues_with_audio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pretotypeanalytics",
            name="issues_with_location",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pretotypeanalytics",
            name="issues_with_photo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pretotypeanalytics",
            name="issues_with_video",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pretotypeanalytics",
            name="issues_without_media",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="has_media",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Did user provide media (photo/video/audio)",
            ),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="issue_location",
            field=models.CharField(
                db_index=True,
                default="Location not specified",
                help_text="Where this issue is happening (e.g., 'Surulere, Lagos')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="media_duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds (for video/audio)", null=True
            ),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="media_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Media file size in bytes"
            ),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Photo/Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                ],
                db_index=True,
                help_text="Type of media attached",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pretotypeissue",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="URL to uploaded media file (photo/video/audio)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pretotypeevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page Loaded"),
                    ("cta_hover", "CTA Button Hovered"),
                    ("cta_click", "CTA Button Clicked"),
                    ("scroll_behavior", "Page Scroll"),
                    ("form_displayed", "Form Displayed"),
                    ("form_interaction", "Form Field Interaction"),
                    ("dropdown_opened", "Issue Type Dropdown Opened"),
                    ("issue_type_selected", "Issue Type Selected"),
                    ("location_field_focused", "Location Field Focused"),
                    ("details_field_focused", "Details Field Focused"),
                    ("details_typing", "User Typing in Details"),
                    ("form_validation_error", "Form Validation Error"),
                    ("media_uploaded", "Media File Selected"),
                    ("media_removed", "Media File Removed"),
                    ("media_upload_error", "Media Upload Error"),
                    ("issue_submitted", "Issue Report Submitted"),
                    ("thank_you_displayed", "Thank You Page Shown"),
                    ("contact_field_focused", "Contact Field Focused"),
                    ("checkbox_clicked", "Opt-in Checkbox Clicked"),
                    ("contact_submitted", "Contact Details Submitted"),
                    ("funnel_completed", "Full Funnel Completed"),
                    ("page_exit", "User Left Page"),
                    ("form_abandoned", "Form Abandoned"),
                    ("back_button", "Back Button Pressed"),
                    ("tab_switch", "Switched to Another Tab"),
                    ("javascript_error", "JavaScript Error"),
                    ("network_error", "Network/API Error"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="pretotypeissue",
            index=models.Index(
                fields=["issue_location", "submitted_at"],
                name="pretotype_i_issue_l_443d06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pretotypeissue",
            index=models.Index(
                fields=["media_type", "submitted_at"],
                name="pretotype_i_media_t_7ae160_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pretotypeissue",
            index=models.Index(
                fields=["has_media", "submitted_at"],
                name="pretotype_i_has_med_14847e_idx",
            ),
        ),
    ]
