# Generated by Django 5.2.5 on 2025-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tpsq", "0006_remove_pretotypeissue_pretotype_i_has_ima_99cf91_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pretotypeissue",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Photo/Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                ],
                db_index=True,
                help_text="Type of media attached",
                max_length=10,
                null=True,
            ),
        ),
    ]
